language: objective-c
osx_image: xcode8.2

script:
    - xcodebuild -workspace DataMapper.xcworkspace -scheme DataMapper -sdk iphonesimulator build-for-testing
    - xctool -workspace DataMapper.xcworkspace -scheme DataMapper -sdk iphonesimulator run-tests
    - pod lib lint

notifications:
    slack: brightify:00rIGJIfWqG5RyWCVoRNEgxt
